// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsdaIb79KGF0u3sSuFoGJaAMNoaCR8ZjY',
    appId: '1:517429811328:web:25aecebb84e3a34d502e65',
    messagingSenderId: '517429811328',
    projectId: 'goaraa-350af',
    authDomain: 'goaraa-350af.firebaseapp.com',
    storageBucket: 'goaraa-350af.appspot.com',
    measurementId: 'G-LG3FCEBNSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwpL0hOoirCqxQKDlIkvBTVbwHLhsYx_8',
    appId: '1:517429811328:android:004aff26a8c0beaa502e65',
    messagingSenderId: '517429811328',
    projectId: 'goaraa-350af',
    storageBucket: 'goaraa-350af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcTjoX7UGCj31w27oDcLj-N9h-9hdAXZo',
    appId: '1:517429811328:ios:998c269f1aaa5d28502e65',
    messagingSenderId: '517429811328',
    projectId: 'goaraa-350af',
    storageBucket: 'goaraa-350af.appspot.com',
    iosBundleId: 'com.example.goaraaAppEg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcTjoX7UGCj31w27oDcLj-N9h-9hdAXZo',
    appId: '1:517429811328:ios:998c269f1aaa5d28502e65',
    messagingSenderId: '517429811328',
    projectId: 'goaraa-350af',
    storageBucket: 'goaraa-350af.appspot.com',
    iosBundleId: 'com.example.goaraaAppEg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsdaIb79KGF0u3sSuFoGJaAMNoaCR8ZjY',
    appId: '1:517429811328:web:039606c0db148240502e65',
    messagingSenderId: '517429811328',
    projectId: 'goaraa-350af',
    authDomain: 'goaraa-350af.firebaseapp.com',
    storageBucket: 'goaraa-350af.appspot.com',
    measurementId: 'G-FYSV382QP1',
  );
}
